namePrefix: mdw20-us-premium-
nameSuffix: "-0"

commonLabels: 
  replica-set: MDW20-us-premium

bases:
- ../../../../base

patchesJSON6902:
- target:
    version: v1
    kind: Service
    name: mongod
  patch: |-
    - op: replace
      # ~1 is "/" in JSON Patch
      path: /spec/selector/statefulset.kubernetes.io~1pod-name
      value: mdw20-us-premium-mongod-0