apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos
  labels:
    app: mongos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongos
  template:
    metadata:
      labels:
        app: mongos
    spec:
      containers:
      - name: mongos
        image: payxdemo.azurecr.io/mongodb-enterprise:latest
        command:
          - mongos
          - --configdb
          - $(CONFIG_REPLICA_SET_NAME)/$(CONFIG_REPLICA_SET_MEMBERS)
          - --port
          - "27017"
          - --bind_ip_all
          - --tlsMode
          - disabled
          - --keyFile
          - /config/keyfile
        env:
          - name: CONFIG_REPLICA_SET_NAME
            valueFrom:
              configMapKeyRef:
                name: mongo-shared-config
                key: config-replica-set-name
          - name: CONFIG_REPLICA_SET_MEMBERS
            valueFrom:
              configMapKeyRef:
                name: mongos-shared-config
                key: config-replica-set-members
        ports:
          - containerPort: 27017
            name: mongo
        volumeMounts:
          - name: mongo-shared-secrets
            mountPath: /config
      volumes:
        - name: mongo-shared-secrets
          secret:
            secretName: mongo-shared-secrets
            defaultMode: 256
            items:
            - key: keyfile
              path: keyfile
