apiVersion: v1
kind: Service
metadata:
  labels:
    deployment-name: mongos
  name: mongos
spec:
  type: LoadBalancer
  selector:
    app: mongos
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
