apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: mdw20-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mdw20-app
    spec:
      containers:
        - name: mdw20-app
          image: payxdemo.azurecr.io/mdw20-app
          ports:
            - containerPort: 8080
