namePrefix: mdw20-us-

commonLabels: 
  replica-set: MDW20-us

bases:
- ../../../base

patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: mongod
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/command/3
      value: MDW20-us