---
apiVersion: v1
kind: Service
metadata:
  # annotations:
  #   external-dns: EXTERNAL_DNS
  labels:
    # replica-set: REPLICA_SET_NAME
    # pod-name: POD_NAME
  name: mongod
spec:
  type: LoadBalancer
  # loadBalancerIP: PUBLIC_IP
  # externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
